### ISSUE TITLE
Remove cooldowns in Anime Command

### ISSUE THREAD

**Issue by Sebas-ti-an** [maisans-maid/Mai#1]
The anime commands looks cramped. Waiting every 10 seconds is a pain for every command. Please remove this as it will make your Bot service the users better

**Comment by firefly-rrp** [comment]
I don't think that would be a good idea. The author might've done this to avoid being rate limited. Rate Limits are common when fetching data from anime databases. 10 seconds is even a generous trade-off for the rate-limit concern ~
