### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by buttermiilk** [maisans-maid/Mai#103]
Uh, if I try to make some sort of NSFW commands in a separate group, how can I hide it when executing m!help in non-NSFW channels?
(I know this question is silly, meh)

**Comment by maisans-maid** [comment]
Making these commands in a seperate group is the easiest way to do this:
In your commandfile, the group should be a nsfw tag or any tag you like to consider nsfe
```js
group: 'nsfw',
```

Then, make sure that in your index.js file, the group name is included:
```js
paths: [
    'action', 'anime', 'bot',
    'core', 'fun', 'moderation', 'music',
    'owner', 'setup', 'social','utility', 'nsfw'
  //                                         ^ right here
    ]
```
After this, you can hide the group when executing help command by filtering the group out
Inject this code under [help.js#L72](https://github.com/maisans-maid/Mai/blob/master/commands/core/help.js#L72)
```js
if (command.group === 'nsfw'){
  return message.channel.send('oh no, this is a nsfw command!')
};
```
That will work for all cases, but if you want the command to be hidden only on non-nsfw channels, you can add a condition like:
```js
if (command.group === 'nsfw' && !message.channel.nsfw){
  return message.channel.send('oh no, this is a nsfw command!')
};
```

You can disable the nsfw command group or any command group from appearing on `cmd` command aswell by filtering out the group before mapping them out:
[commands.js#L20](https://github.com/maisans-maid/Mai/blob/master/commands/core/commands.js#L20) already filters out unspecified command groups (commands that were configured without a group variable), you can add the 'nsfw' group or whatever you named the command group to be excluded from the list.
```js
for (const group of Object.keys(client.commands.groups).filter(g => !['unspecified', 'nsfw'].includes(g)))
//                                                                                      ^ group name to exclude here

**Comment by buttermiilk** [comment]
I've tried applying the last line for cmd.js, and instead of using if-else to hide the NSFW category in non-NSFW channels, I wanna know if I can use something else shorter?

**Comment by buttermiilk** [comment]
I might send the code if you wish.

**Comment by maisans-maid** [comment]
> I've tried applying the last line for cmd.js, and instead of using if-else to hide the NSFW category in non-NSFW channels, I wanna know if I can use something else shorter?

If you mean to display the nsfw commands in a nsfw channel, you can add a condition in the filter without using if-else
```js
// Excludes nsfw on all channels
for (const group of Object.keys(client.commands.groups).filter(g => !['unspecified', 'nsfw'].includes(g)))
//                                                                                      ^ group name to exclude here

// Excludes nsfw on all channels except nsfw
const filternsfw = (nsfw) => nsfw === 'nsfw' ? message.channel.nsfw ? true : false : true;
// nsfw === 'nsfw'              -> Checks if the group name is nsfw
// message.channel.nsfw         -> Checks if the channel is nsfw
// true                         -> Do not filter out if the channel is not nsfw
// false                        -> Filter out if group name is nsfw and channel is nsfw
// true                         -> Do not filter out if group name is not nsfw
for (const group of Object.keys(client.commands.groups).filter(g => g !== 'unspecified' || filternsfw(g))){
//                                                                                              ^ use the function here
```
I have not tested the code on the local machine, but the logic should work

**Comment by buttermiilk** [comment]
Doesn't seem to work, actually. I guess I'll use if-else for that.

**Comment by buttermiilk** [comment]
Thanks for your help!
