### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by buttermiilk** [maisans-maid/Mai#108]
How can I map out all the available commands?

This line didn't provide what I expected: 
```js
client.commands.registers
```
And I also used
```js
for (const group of Object.keys(client.commands.groups)) {
      client.commands.groups.get(group).map(x => x.name)
      }
```
but it didn't work as I expected, too.

EDIT: Fix misspelled stuff.

**Comment by maisans-maid** [comment]
you spelled it incorrectly, it should work using `client.commands.groups` instead of `client.commands.group`.

Also, it should be `Object.keys()` instead of `Object.key()`

**Comment by buttermiilk** [comment]
Lol, I actually forgot to check what was I typing. I meant, I expected something different that I can use levenshtein algorithm to compare the usable command(s) with the misspelled one.
