### ISSUE TITLE
issues with comands

### ISSUE THREAD

**Issue by anime731** [maisans-maid/Mai#116]
srry for bothering you but i need your help each time i set up a welcome channel or trying to setup welcome msg, xpreset, xpexcempt, xpenable, welcometoggle, watch, userxpreset, setwelcomech, setsuggestch, prefix, setgoodbyemsg, disableanisched, goodbyetoggle, nonxpchannels, market, leaderboard, inventory, buy, bank i hope you get these fix bc i need help

**Comment by anime731** [comment]
it always say connect to database bot how

**Comment by BearTS** [comment]
check the env example and fill it up with MONGO URI. 
@anime731

**Comment by BearTS** [comment]
@maisans-maid i think this should be closed
