### ISSUE TITLE
Dotenv install error

### ISSUE THREAD

**Issue by tzt345** [maisans-maid/Mai#120]
**Describe the bug**
I can't install dotenv on glitch/heroku
![Screenshot_2021-06-02-15-52-55-08](https://user-images.githubusercontent.com/83703996/120444883-a5ec6b00-c3ba-11eb-9d0d-583b9ab0ff7a.png)

**To Reproduce**

**Expected behavior**
Whenever I try to install dotenv I get the error

**Screenshots**
Screenshot Is On the top

**Additional context**

**Comment by kakarot-dev** [comment]
That is not dotenv error

**Comment by kakarot-dev** [comment]
It is a discord js error
Go to package.json and find discord.js and replace it’s version with v12.5.3

EXAMPLE:  "discord.js": "^12.5.3"

**Comment by tzt345** [comment]
> It is a discord js error
> Go to package.json and find discord.js and replace it’s version with v12.5.3
> 
> EXAMPLE: "discord.js": "^12.5.3"

OMG Thank You!!!!!

**Comment by Krxzy** [comment]
hey, i done this now im getting this error,

C:\Users\midla\Downloads\Mai-master>npm i dotenv
npm ERR! code EJSONPARSE
npm ERR! file C:\Users\midla\Downloads\Mai-master\package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected string in JSON at position 727 while parsing '{
npm ERR! JSON.parse   "name": "mai",
npm ERR! JSON.parse   "version": "4.1.0",'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

any help? ive redownloaded and ive edited the discord.js thingy to the ver.

**Comment by maisans-maid** [comment]
Your package.json file does not conform to the json [syntax rules](http://www-db.deis.unibo.it/courses/TW/DOCS/w3schools/json/json_syntax.asp.html). Check the validity of your json file [**__here__**](https://jsonformatter.curiousconcept.com/#).

**Comment by Krxzy** [comment]
yes i just found out, after i pasted, i just saw i forgot to add the "," at then end. anw thanks for tryna help also music doesnt work. it says the thing is outdated and when i update it, it says the same thing

**Comment by Krxzy** [comment]
wrong bot srry, dont mind the music part
