### ISSUE TITLE
Font Request

### ISSUE THREAD

**Issue by Aayansh549** [maisans-maid/Mai#128]
Which font is used at Mai's Profile Card which is in Use Nowadays. Because I tried something like Rank Card but there it shows Sqaure Blocks instead of the Name which contains other Characters then Normal. I also wants to use that font in my Canvs so that it will not show Square Blocks. They look ugly on it.
![1625124644435_0_profile](https://user-images.githubusercontent.com/81318819/124084447-9c632b00-da6c-11eb-9ac6-94a1d57ad80d.png)

**Comment by kakarot-dev** [comment]
the new mai is now closed source (hopefully opened source in the future) 😄

**Comment by Aayansh549** [comment]
> the new mai is now closed source (hopefully opened source in the future) 😄

So can I just know how to make those characters to show in name at Canvas

**Comment by maisans-maid** [comment]
So those square blocks are the fallback for unicode that doesn't have the style in the canvas module. They are called [Unicode BMP Fallback SIL](https://www.fontspace.com/unicode-bmp-fallback-sil-font-f13379) which is intended for debugging. If you want to get rid of this, every unicode you use should have their appropriate fonts registered on the canvas module. First thing you do is find the style you're looking for, which should support the basic unicodes, this is for the styling. Then, find a font with over 60k glyphs for the fallback function. There's a font called [Unifont](http://unifoundry.com/unifont/) that supports most, if not all, of the glyphs. Then, you can dig deeper for a font file that supports multiple glyphs. 

I'll be rewriting this code when v13 of djs releases so you can either search for the font yourself or wait for the official public release.

**Comment by Aayansh549** [comment]
> So those square blocks are the fallback for unicode that doesn't have the style in the canvas module. They are called [Unicode BMP Fallback SIL](https://www.fontspace.com/unicode-bmp-fallback-sil-font-f13379) which is intended for debugging. If you want to get rid of this, every unicode you use should have their appropriate fonts registered on the canvas module. First thing you do is find the style you're looking for, which should support the basic unicodes, this is for the styling. Then, find a font with over 60k glyphs for the fallback function. There's a font called [Unifont](http://unifoundry.com/unifont/) that supports most, if not all, of the glyphs. Then, you can dig deeper for a font file that supports multiple glyphs.
> 
> I'll be rewriting this code when v13 of djs releases so you can either search for the font yourself or wait for the official public release.

Thanks a lot for Info. Means it will be published officially after v13 Release of Discord.js?

**Comment by kakarot-dev** [comment]
Not exactly right after, it will be but it’ll be public in due time

**Comment by BearTS** [comment]
> > So those square blocks are the fallback for unicode that doesn't have the style in the canvas module. They are called [Unicode BMP Fallback SIL](https://www.fontspace.com/unicode-bmp-fallback-sil-font-f13379) which is intended for debugging. If you want to get rid of this, every unicode you use should have their appropriate fonts registered on the canvas module. First thing you do is find the style you're looking for, which should support the basic unicodes, this is for the styling. Then, find a font with over 60k glyphs for the fallback function. There's a font called [Unifont](http://unifoundry.com/unifont/) that supports most, if not all, of the glyphs. Then, you can dig deeper for a font file that supports multiple glyphs.
> > I'll be rewriting this code when v13 of djs releases so you can either search for the font yourself or wait for the official public release.
> 
> Thanks a lot for Info. Means it will be published officially after v13 Release of Discord.js?

Sorry we wont be making the djs v13 version of Mai public, it is now closed source.
