### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by Nejkira** [maisans-maid/Mai#132]
I tried reinstalling node.js, even tried previous versions of Mai
but I still failing at install.

There's log:
https://www.pastebin.cz/cs/p/fELtN73

**Comment by kakarot-dev** [comment]
wth is that

give us the specefic log not the whole damn node install logs.

As for your question, can you make sure youre using node 14

**Comment by Nejkira** [comment]
This is copy and paste from console:
https://www.pastebin.cz/en/p/ikFFtyE

I have node.js 14

 Nejde otevřít soubor zahrnout = Unable to open file include

**Comment by kakarot-dev** [comment]
The “copy paste” too long, give the specefic part the code is erring

**Comment by Nejkira** [comment]
ERR part:
https://www.pastebin.cz/en/p/bDwi3GW

**Comment by maisans-maid** [comment]
make sure to install the windows build tools
```
npm install --global --production windows-build-tools
```

**Comment by kakarot-dev** [comment]
lol, i forgot to respond and yea use the above command in your terminal but make sure you have admin access

**Comment by Nejkira** [comment]
I installed the windows build tools and succesfully installed bot prequisities but I keep getting

This code error:
https://www.pastebin.cz/en/p/2eDk6WE

**Comment by maisans-maid** [comment]
> https://github.com/maisans-maid/Mai/blob/master/commands/social/resumeStreak.js#L28

Seems like this is on the source code. Conqr created that particular section. You can fix it yourself tho, just add an additional closing parenthesis on that line

```diff
- if(isNaN(Number(streakMessage)) {
+ if(isNaN(Number(streakMessage))) {
```

**Comment by Nejkira** [comment]
> 
> 
> > https://github.com/maisans-maid/Mai/blob/master/commands/social/resumeStreak.js#L28
> 
> Seems like this is on the source code. Conqr created that particular section. You can fix it yourself tho, just add an additional closing parenthesis on that line
> 
> ```diff
> - if(isNaN(Number(streakMessage)) {
> + if(isNaN(Number(streakMessage))) {
> ```

It works! Thanks!
