### ISSUE TITLE
Execute error

### ISSUE THREAD

**Issue by incamilo** [maisans-maid/Mai#134]
I have this error in console when trying to run Mai 
[Error Code](https://pastebin.pl/view/63104537)

**Comment by kakarot-dev** [comment]
Make sure to install canvas
also if not possible try this, then do `npm i`

```
npm install --global --production windows-build-tools
```

**Comment by incamilo** [comment]
> Asegúrese de instalar el lienzo
> también, si no es posible, intente esto, luego hágalo`npm i`
> 
> ```
> npm install --global --production windows-build-tools
> ```

I work from android with termux because I don't have access to a PC, I can't install windows-build-tools

**Comment by kakarot-dev** [comment]
then do npm install
and make sure its installing canvas

**Comment by buttermiilk** [comment]
> > Asegúrese de instalar el lienzo
> > también, si no es posible, intente esto, luego hágalo`npm i`
> > 
> > ```
> > npm install --global --production windows-build-tools
> > ```
> 
> I work from android with termux because I don't have access to a PC, I can't install windows-build-tools

Unfortunately, you can't install `canvas` on an Android device. The permission system is different there.
I don't know if there is any workaround, but Google is your best friend. Let me know if you have any temporary solution.

**Comment by buttermiilk** [comment]
You can just remove the dependency and delete `profile.js` in commands/social, everything will work as normal.

**Comment by buttermiilk** [comment]
Also, refer to [this link](https://github.com/Automattic/node-canvas/issues/1609) for more information.

**Comment by kakarot-dev** [comment]
> > > Asegúrese de instalar el lienzo
> > > también, si no es posible, intente esto, luego hágalo`npm i`
> > > ```
> > > npm install --global --production windows-build-tools
> > > ```
> > 
> > 
> > I work from android with termux because I don't have access to a PC, I can't install windows-build-tools
> 
> Unfortunately, you can't install `canvas` on an Android device. The permission system is different there.
> I don't know if there is any workaround, but Google is your best friend. Let me know if you have any temporary solution.

You should know he specifically said termux so I’m guessing he’s connecting to a computer in the cloud

**Comment by maisans-maid** [comment]
Check  [this issue (node-canvas/#1687)](https://github.com/Automattic/node-canvas/issues/1687) on automattic that references [this issue (node-canvas/#1609)](https://github.com/Automattic/node-canvas/issues/1609).

**Comment by BearTS** [comment]
are you emulating Ubuntu ? If yes refer to https://github.com/Automattic/node-canvas#compiling

**Comment by BearTS** [comment]
@maisans-maid this should be closed since this isn't an issue from our side, but an issue with building node-canvas
