### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by Hachiiki** [maisans-maid/Mai#139]
const channelID = channel.match(/\d{17,19}/)?.[0];

?. and ;

in setanischedch

**Comment by maisans-maid** [comment]
Update node version to at least lts

**Comment by Hachiiki** [comment]
> Update node version to at least lts

well since replit don't have other version of nodes I tried to do this

`let channel = message.mentions.channels.first() || client.guilds.cache.get(message.guild.id).channels.cache.get(args[0]) || message.guild.channels.cache.find(c => c.name.toLowerCase() === args.join(' ').toLocaleLowerCase());`

it work perfectly and set the channel

**Comment by kakarot-dev** [comment]
how is this a ts error?

**Comment by BearTS** [comment]
> how is this a ts error?

Yeah lol, that's what i thought

**Comment by BearTS** [comment]
> > Update node version to at least lts
> 
> well since replit don't have other version of nodes I tried to do this
> 
> `let channel = message.mentions.channels.first() || client.guilds.cache.get(message.guild.id).channels.cache.get(args[0]) || message.guild.channels.cache.find(c => c.name.toLowerCase() === args.join(' ').toLocaleLowerCase());`
> 
> it work perfectly and set the channel

We Highly recommend you using the public docker images that are available

**Comment by Hachiiki** [comment]
> how is this a ts error?

it just showed there, I was using replit node v12.3.1

**Comment by kakarot-dev** [comment]
well ok, upgrade the node version, or use the docker image that bear made 👍

**Comment by kakarot-dev** [comment]
I believe the issue is fixed and can be closed now

**Comment by BearTS** [comment]
@maisans-maid Yeah, I believe we can close this.
