### ISSUE TITLE
ERROR: FFMPEG is not installed

### ISSUE THREAD

**Issue by makarasty** [maisans-maid/Mai#140]
ERROR: FFMPEG is not installed. 
Install with "npm install ffmpeg-static" or download it here: https://ffmpeg.org/download.html.

I have installed `ffmpeg` locally and with `npm install ffmpeg-static` but it doesn't help

![изображение](https://user-images.githubusercontent.com/71918286/184548271-5aead64e-02ce-40cd-b714-96a158358122.png)

**Comment by BearTS** [comment]
@makarasty this is not an issue related to the bot script
You have to install ffmpeg to your server

Follow this:
https://linuxize.com/post/how-to-install-ffmpeg-on-debian-9/


Refrain to making issues like this in future

**Comment by makarasty** [comment]
@BearTS I think the problem is in the bot, because the other bot sees the installed ffmpeg

![изображение](https://user-images.githubusercontent.com/71918286/184551735-62aeb757-32aa-41e8-8828-48b569517b2e.png)

**Comment by maisans-maid** [comment]
try `npm ls ffmpeg-static` in the console then show us the logs

**Comment by makarasty** [comment]
@maisans-maid Sorry for the long reply 

_about prism-media I was trying to get the bot to see ffmpeg, I can delete prism-media as it did nothing_

![изображение](https://user-images.githubusercontent.com/71918286/184625969-a86b0c8e-87a0-4a76-a584-f8cc2cf340ee.png)

**Comment by BearTS** [comment]
@makarasty use the docker public image [here](https://hub.docker.com/r/bearts/mai)

**Comment by makarasty** [comment]
I don't know how to use docker, I need help with ffmpeg

**Comment by makarasty** [comment]
@BearTS I don't know how to use docker, I need help with ffmpeg!

**Comment by BearTS** [comment]
@makarasty Just install docker desktop and then fill the [docker-compose](https://github.com/maisans-maid/Mai/blob/master/docker-compose.yml) and then run `docker-compose up` inside the folder
Due to issues like the one that you are facing, we have added support for docker

**Comment by makarasty** [comment]
@BearTS > 

Can I host the bot without using docker?

**Comment by kakarot-dev** [comment]
You can, but the issue here is that 
- The code is outdated
- We don’t provide help for personal hosting, and since this is a issue related to ur local machine, we can’t provide help

You can use the commands mentioned in the docker file to set the bot up locally.
Incidentally, we do provide support in hosting with docker

**Comment by makarasty** [comment]
I am very disappointed.
