### ISSUE TITLE
Economy and Levelling

### ISSUE THREAD

**Issue by Lelouchq** [maisans-maid/Mai#2]
Do you have a discord server???

also how do you make the economy and leveling work???

**Comment by maisans-maid** [comment]
you can toggle the leveling feature of the bot through `m!ps xptoggle`. Alternatively, you can do `m!ps` to view all the subcommands for the pointsystem feature.

You can also join Mai's Dev server @ https://discord.gg/P9gj82x

**Comment by kyoyacchi** [comment]
cool
