### ISSUE TITLE
I think Reddit changed their JSON

### ISSUE THREAD

**Issue by buttermiilk** [maisans-maid/Mai#4]
A few days ago I've done the command m!animeme and m!reddit, and both of them works just fine
Today I didn't see any response, and when I check the same code on my another bot, it says `cannot read property 'children' of undefined`
Can you fix that?

**Comment by buttermiilk** [comment]
Checked again, the subreddit is private

**Comment by maisans-maid** [comment]
Will change the subreddit in the next bot startup
