### ISSUE TITLE
Item still being used despite it already sold

### ISSUE THREAD

**Issue by firefly-rrp** [maisans-maid/Mai#44]
**Describe the bug**
When selling something you already equipped, the item still shows up on the profile

**To Reproduce**
1. Buy an item
2. Equip the item
3. Use profile command
4. Sell the item
5. Use profile command again
6. Watch the bot still display the item

**Expected behavior**
The item should revert to default.

**Screenshots**

**Additional context**

**Comment by maisans-maid** [comment]
This is fixed. Thank you for reporting this issue
