### ISSUE TITLE
Another small bug!

### ISSUE THREAD

**Issue by buttermiilk** [maisans-maid/Mai#61]
**Describe the bug**
Users without description in AL makes the bot fails to send info. I don't know is there any effective way to fix this, but you can make a small function that checks the user description before sending info.

**To Reproduce**
You don't need to do anything, try `m!alprofile Jikan` and you'll receive the error in the console.
My console error:
```
TypeError: Cannot read property 'replace' of null
    at Command.run (path_to_cmd\commands\anime\alprofile.js:47:69)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Expected behavior**
Yea, I expected the error to not happen and the bot successfully sends the message.

**Screenshots**
I think I don't need to take screenshot since it's very easy to reproduce.

**Comment by maisans-maid** [comment]
Yipp thanks for the report, though function checking is not needed, an optional chaining operator will do the job just fine.

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
you can just kill it, I mean small bugs don't bite, just step on it!
