### ISSUE TITLE
OsyAndPrestonGotGroun-ded

### ISSUE THREAD

**Issue by ThatsCoolGuysHaha-azertyyy** [maisans-maid/Mai#67]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
> What is this even about?

it's a celebration that I groun-de-d Osy and pre-st-on, bear that doesn't bite in an indian zoo. WOOOOOHOOOOOO!!!!!!!

**Comment by BearTS** [comment]
You can't make Invalid issue on random repos......

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
well I have a life, and Reality can be whatever I want.

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
What's happening, you my ask?

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
well,

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@ThatsCoolGuysHaha-azertyyy 
Learn Git and GitHub without any code!
Using the Hello World guide, you’ll start a branch, write comments, and open a pull request.


maisans-maid
/
Mai
8
2514
Code
Issues
1
Pull requests
2
Actions
Projects
Wiki
Security
Insights
OsyAndPrestonGotGroun-ded #67
 Open
ThatsCoolGuysHaha-azertyyy opened this issue 22 minutes ago · 3 comments
 Open
OsyAndPrestonGotGroun-ded
#67
ThatsCoolGuysHaha-azertyyy opened this issue 22 minutes ago · 3 comments
Comments
@ThatsCoolGuysHaha-azertyyy
 
ThatsCoolGuysHaha-azertyyy commented 22 minutes ago
Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Additional context
Add any other context about the problem here.

@BearTS
 
Contributor
BearTS commented 9 minutes ago
What is this even about?

@ThatsCoolGuysHaha-azertyyy
 
Author
ThatsCoolGuysHaha-azertyyy commented 2 minutes ago
What is this even about?

it's a celebration that I groun-de-d Osy and pre-st-on, bear that doesn't bite in an indian zoo. WOOOOOHOOOOOO!!!!!!!

@BearTS
 
Contributor
BearTS commented 32 seconds ago
You can't make Invalid issue on random repos......

@ThatsCoolGuysHaha-azertyyy

 
 
Leave a comment
No file chosen
New Video support! Upload MP4 and MOV file types. Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Linked pull requests
Successfully merging a pull request may close this issue.

None yet
Notifications
Customize
You’re receiving notifications because you authored the thread.
2 participants
@BearTS
@ThatsCoolGuysHaha-azertyyy
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
and, OH SO YOUR A NON BITING BEAR? NAME EVERYONE WHO MET WITHOUT BITING!

**Comment by BearTS** [comment]
@maisans-maid i request you close this issue and ban this user from opening issues in future

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
> @maisans-maid i request you close this issue and ban this user from opening issues in future

just sh-u.t up! imma ground you with 0.Sy a-nd pr-es.t0n! NOW!

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
OOOOOOOOOOOOOOOOOOOOOOOOOOOO! BEARTS HOW DARE YOU WANT TO BLOCK ME! THAT'S IT YOUR GROUNDED GROUNDED GROUNDED GROUNDED FOR 6590876083 YEARS WITH PRE-ST.0N AND OSY!! GO TO YOUR ZOO NOW!

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
> @maisans-maid i request you close this issue and ban this user from opening issues in future

and SHE WOULDNT RESPOND TO YOU LMFAO! SHES TOO WEEBY TO BLOCK ME CUZ SHES WATCHING ANIME SINCE LAST NIGHT!!!! 🖕🏿

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by ThatsCoolGuysHaha-azertyyy** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣
