### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by buttermiilk** [maisans-maid/Mai#9]
So how can I work on per-guild prefix?

It'll be convenient if you have a premade code, but you can show me what should I add/remove/fix to do that if you don't.
It's fine if you can't help because of something, I'm working on it.

Thanks.

**Comment by maisans-maid** [comment]
you have to make a new mongoose model (schema) to save those per-guild prefixes. Save the prefix along with the guild ID as a string (large numbers don't work well with JS). Make a code that checks both the default and the guild-based prefix on your message event (particularly in the command handler)
