### ISSUE TITLE
Move MAI to a github organisation

### ISSUE THREAD

**Issue by yigitkerem** [maisans-maid/Mai#99]
The title is extremely self-explanatory.

**Comment by maisans-maid** [comment]
No plans yet and no reason to do so.

**Comment by maisans-maid** [comment]
However, i'll keep it open for the meantime so it won't be forgotten

**Comment by blazklemencic** [comment]
sed organisation is cool

**Comment by maisans-maid** [comment]
We will now begin mai to move on [this](https://github.com/mai-bot) organization. The team is also getting big.

**Comment by Noah670** [comment]
Hey can I help contribute and join the organization?

**Comment by kakarot-dev** [comment]
Just wanted to ask what are the advantages?

**Comment by maisans-maid** [comment]
> Hey can I help contribute and join the organization?

may i know the reason you'd like to help?

> Just wanted to ask what are the advantages?

None.

**Comment by yigitkerem** [comment]
> > Hey can I help contribute and join the organization?
> 
> may i know the reason you'd like to help?
> 
> > Just wanted to ask what are the advantages?
> 
> None.

It just seemed like you were saying there was no reason that they would like to help in the email for a moment. Github should really consider adding the quotes to emails.

**Comment by Noah670** [comment]
> > Hey can I help contribute and join the organization?
> 
> may i know the reason you'd like to help?
> 
> > Just wanted to ask what are the advantages?
> 
> None.

I want to help contribute to the project and make the bot even better!

**Comment by maisans-maid** [comment]
> > > Hey can I help contribute and join the organization?
> > 
> > 
> > may i know the reason you'd like to help?
> > > Just wanted to ask what are the advantages?
> > 
> > 
> > None.
> 
> I want to help contribute to the project and make the bot even better!

its a great help if you'd to be introduced to the team. However, i can't decide on it on my own. You could join the support server [here](https://support.mai-san.ml/) first then we'll talk what to do onwards. I mean, like, working on specific parts and all.

**Comment by conqr2** [comment]
Closing this issue. Bot has already been moved, if you want to help out please contact us through the email listed on the @mai-bot org ([https://github.com/mai-bot](https://github.com/mai-bot)) or through our Discord server, listed on our website [https://mai.gg](https://mai.gg).
